# Generated by Django 4.2.1 on 2023-05-27 02:42

import Authentication.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CusUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('artist', models.CharField(blank=True, max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=Authentication.models.avatar_random_path)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=Authentication.models.cover_image_random_path)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('short_bio', models.TextField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('gender', models.CharField(choices=[('0', 'Nam'), ('1', 'Nữ'), ('2', 'Khác')], default='2', max_length=1)),
                ('address', models.CharField(blank=True, max_length=30)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_status', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='user_groups', related_query_name='user', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_permissions', related_query_name='user', to='auth.permission')),
            ],
            options={
                'verbose_name': 'CusUser',
                'verbose_name_plural': 'CusUsers',
                'db_table': 'CusUser',
                'ordering': ['id'],
            },
        ),
    ]
